### ISSUE TITLE
Form Theming Strategy

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-ui-components#318]
I've been pushing forward with a React ThemeProvider theming method, but @kaitmore reminds me there are other strategies available, and we should discuss and have a plan before making major moves that will set the direction and lock us into anything for the lifespan of the library.

**Comment by kaitmore** [comment]
I would like to give styled-system a test run https://varun.ca/styled-system/ I like this solution a lot because it is flexible, but stays within predetermined theming boundaries.

This is a slightly different approach than what @shanberg has done so far.  Here's what we would need to accomplish:

1) Refactor the theme object Stuart created [here](https://github.com/DecipherNow/gm-ui-components/pull/365/files#diff-129a3223313b2586975ecf68c1c9717b) into something like this:
![image](https://user-images.githubusercontent.com/22768918/46347727-93727000-c61a-11e8-9fd2-169c30e2a612.png)

2) Abstract our hover/focus/active/disabled styles and include those in the theme object as well

3) [Implement system-components](https://github.com/jxnblk/styled-system/tree/master/system-components) which allows you to set default values & reuse styles on other element types using the `is` prop (although that will be pretty irrelevant soon when s-c 4.0 is out of beta).   

![image](https://user-images.githubusercontent.com/22768918/46348675-bc483480-c61d-11e8-9efe-46415bd9f412.png)

**Comment by shanberg** [comment]
OBE
