### ISSUE TITLE
i18n Support?

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-ui-components#407]
How can we plan to support internationalization in our components?

**Comment by kaitmore** [comment]
i18n should be handled by the consuming app. The component library just needs to make sure that all text can be set through props and that there isn't anything hardcoded, so that the developer can pass in calls to `intl.formatMessage` (or whatever the equivalent is if they're not using `react-intl`). I've done my best to make sure this is happening already, if you see any components that don't follow this pattern let me know.

**Comment by 7ruth** [comment]
What is the best way to handle cases when I need to have i18n messages in placeholders and labels?

**Comment by tilleryd** [comment]
Yeah, I'm with @kaitmore on this for the following reasons:

1. we want to keep the library small, adding `react-intl` and messages will bloat it significantly
2. we want to avoid peer dependency issues so keeping `react-intl` out will help
3. the small amount of translated text wouldn't justify the i18n because consuming apps will likely pass their own labels rather than using the defaults

**Comment by 7ruth** [comment]
How does mandate of keeping gm-ui-components small interact with Chris H's desire to put more complex components that do have many peer dependencies into the lib for use on wide range of future commercial and govt projects? (He basically wants storybook from https://github.com/DecipherNow/gm-data-ui to be part of gm-ui-components from what I understood from his guidance)

**Comment by tilleryd** [comment]
@7ruth The goal of this library is to provide atomic components (building blocks). Ideally there would be little to no dependencies, from a deployed library perspective. If there are general components that fit the atomic model then we will consider them for addition to the library. You can create a Component Proposal type issue. We can discuss the addition of dependencies on a case by case basis. I assume some, not all of the components from gm-data-ui would make it into this library. Otherwise we may need to create another library with more advanced, specialized components.

**Comment by 7ruth** [comment]
@tilleryd understood. Sounds like 'drive 2.0' team needs a separate ui-component-lib with a goal of providing flexibility to rapidly build complex and modular UIs across commercial and govt environments. It will have many dependencies and won't be atomic, but rather build up from atomic components provided by gm-ui-lib.
