### ISSUE TITLE
Make appFooter more generic

### ISSUE THREAD

**Issue by 7ruth** [DecipherNow/gm-ui-components#420]
Component: appFooter

## Will this modification effect the existing functionality?

- Yes

## Describe your proposed change

- User should have ability to override and insert their own content into the footer

**Comment by kaitmore** [comment]
@7ruth Do you have any opinions on the implementation? I'm thinking we could go 2 ways with this 

- refactor Footer so there is a FooterLeft, FooterCenter, FooterRight with props that map to each, so that you can choose which section to override
- simply render this.props.children if it's provided instead of the default Decipher footer content (override everything)

**Comment by kaitmore** [comment]
Closed by #423
