### ISSUE TITLE
Make appHeader more generic

### ISSUE THREAD

**Issue by 7ruth** [DecipherNow/gm-ui-components#421]
Component: appHeader

## Will this modification effect the existing functionality?

- Yes

## Describe your proposed change

- User should have the ability to override and insert their own content into the header

**Comment by kaitmore** [comment]
@7ruth Could you be more specific about which parts of the AppHeader you want to override? It seems to be pretty flexible already, but I'm not familiar with your use case.

**Comment by 7ruth** [comment]
![Folder Table](https://user-images.githubusercontent.com/10719152/56764465-bc06b680-6772-11e9-8553-32c4592d05c4.png)

This is an example of the header we would want. Hmm, but looks like you already allow spreading of props to the wrap of the header, so I can probably overwrite the background image mesh and adjust the height... if thats correct, maybe this issue isn't necessary.

**Comment by kaitmore** [comment]
I think these are totally different components altogether, and making one flexible enough to become the other would defeat the goal of code reuse.

I talked to @shanberg about this briefly, and he said that the Drive app header is what he would like the dashboard header to become. Since we're not even using the AppHeader component in the dashboard, I propose we make the Drive header the official AppHeader and let the dashboard catch up eventually. Perhaps you can add this to your list of components to add?

**Comment by 7ruth** [comment]
Sounds good, will do.
